In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Read the CSV file
# Replace 'your_file.csv' with your actual file path
df = pd.read_csv(r'monitoraggio_aria_04_150924_300924.csv')

In [9]:
df3 = pd.read_csv(r'monitoraggio_aria_03_010924-140924.csv')
df4 = pd.read_csv(r'monitoraggio_aria_04_150924_300924.csv')
df5 = pd.read_csv(r'monitoraggio_aria_05_011024-081024.csv')
df = pd.concat([df3,df4,df5], axis=0, ignore_index=True)

In [10]:
import ast
row, col = 21, 7
ast.literal_eval(df[(df['row'] == row) & (df['col'] == col)]['centroid'].iloc[0])['coordinates']

[9.017401684, 39.29311243]

In [11]:
row, col = 25, 9
ast.literal_eval(df[(df['row'] == row) & (df['col'] == col)]['centroid'].iloc[0])['coordinates']

[9.144702998, 39.166869897]

In [12]:
df['centroid'] = df['centroid'].apply(lambda x: ast.literal_eval(x)['coordinates'])
df['lat'] = df['centroid'].apply(lambda x: x[1])
df['lon'] = df['centroid'].apply(lambda x: x[0])
df.drop(columns=['centroid'], axis=1, inplace=True)
df

,row,col,entry_date,geometry,CH4,CO,HCHO,NO2,O3,SO2,lat,lon
0,15,5,2024-09-07T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[8.857534478...",1931.078735,0.033016,0.000314,2.294748e-05,0.135462,0.000475,39.482287,8.889543
1,15,5,2024-09-08T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[8.857534478...",1931.078735,0.029585,0.000147,2.128617e-05,0.130883,-0.000146,39.482287,8.889543
2,15,5,2024-09-09T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[8.857534478...",1923.200684,0.029587,0.000382,3.186791e-05,0.126504,-0.000243,39.482287,8.889543
3,15,5,2024-09-10T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[8.857534478...",1923.200684,0.031236,-0.000039,1.569478e-05,0.139296,0.000570,39.482287,8.889543
4,15,5,2024-09-11T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[8.857534478...",1923.200684,0.036269,0.000107,-3.536028e-07,0.140820,-0.000297,39.482287,8.889543
...,...,...,...,...,...,...,...,...,...,...,...,...
5808,28,14,2024-10-05T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[9.430715591...",NaN,0.031589,0.000061,1.078207e-05,0.140657,-0.000331,39.071426,9.462409
5809,28,14,2024-10-06T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[9.430715591...",NaN,0.031589,0.000061,1.078207e-05,0.131346,-0.000331,39.071426,9.462409
5810,28,14,2024-10-07T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[9.430715591...",NaN,0.031589,0.000079,1.017173e-05,0.127801,0.001389,39.071426,9.462409
5811,28,14,2024-10-08T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[9.430715591...",NaN,0.031598,-0.000033,1.059383e-05,0.126097,-0.000401,39.071426,9.462409
5812,28,14,2024-10-09T00:00:00+00:00,"{""type"":""Polygon"",""coordinates"":[[[9.430715591...",NaN,0.031598,-0.000033,1.059383e-05,0.134462,-0.000401,39.071426,9.462409

In [13]:
df.drop('geometry', axis=1, inplace=True)
df

,row,col,entry_date,CH4,CO,HCHO,NO2,O3,SO2,lat,lon
0,15,5,2024-09-07T00:00:00+00:00,1931.078735,0.033016,0.000314,2.294748e-05,0.135462,0.000475,39.482287,8.889543
1,15,5,2024-09-08T00:00:00+00:00,1931.078735,0.029585,0.000147,2.128617e-05,0.130883,-0.000146,39.482287,8.889543
2,15,5,2024-09-09T00:00:00+00:00,1923.200684,0.029587,0.000382,3.186791e-05,0.126504,-0.000243,39.482287,8.889543
3,15,5,2024-09-10T00:00:00+00:00,1923.200684,0.031236,-0.000039,1.569478e-05,0.139296,0.000570,39.482287,8.889543
4,15,5,2024-09-11T00:00:00+00:00,1923.200684,0.036269,0.000107,-3.536028e-07,0.140820,-0.000297,39.482287,8.889543
...,...,...,...,...,...,...,...,...,...,...,...
5808,28,14,2024-10-05T00:00:00+00:00,NaN,0.031589,0.000061,1.078207e-05,0.140657,-0.000331,39.071426,9.462409
5809,28,14,2024-10-06T00:00:00+00:00,NaN,0.031589,0.000061,1.078207e-05,0.131346,-0.000331,39.071426,9.462409
5810,28,14,2024-10-07T00:00:00+00:00,NaN,0.031589,0.000079,1.017173e-05,0.127801,0.001389,39.071426,9.462409
5811,28,14,2024-10-08T00:00:00+00:00,NaN,0.031598,-0.000033,1.059383e-05,0.126097,-0.000401,39.071426,9.462409
5812,28,14,2024-10-09T00:00:00+00:00,NaN,0.031598,-0.000033,1.059383e-05,0.134462,-0.000401,39.071426,9.462409

In [15]:
df[(21 <= df['row']) & (df['row'] <= 25) & (7 <= df['col']) & (df['col'] <= 9)]

,row,col,entry_date,CH4,CO,HCHO,NO2,O3,SO2,lat,lon
867,21,7,2024-09-07T00:00:00+00:00,1926.995728,0.035737,0.000196,0.000020,0.135583,0.000933,39.293112,9.017402
868,21,7,2024-09-08T00:00:00+00:00,1926.995728,0.030115,0.000344,0.000033,0.130875,-0.000773,39.293112,9.017402
869,21,7,2024-09-09T00:00:00+00:00,1935.190796,0.030255,0.000350,0.000046,0.127542,0.001538,39.293112,9.017402
870,21,7,2024-09-10T00:00:00+00:00,1902.401855,0.034752,-0.000019,0.000023,0.139390,-0.000173,39.293112,9.017402
871,21,7,2024-09-11T00:00:00+00:00,1902.401855,0.036204,0.000148,0.000008,0.141599,0.000210,39.293112,9.017402
...,...,...,...,...,...,...,...,...,...,...,...
5584,25,9,2024-10-05T00:00:00+00:00,NaN,0.024627,0.000109,0.000024,0.141648,-0.000758,39.166870,9.144703
5585,25,9,2024-10-06T00:00:00+00:00,NaN,0.032275,0.000109,0.000024,0.134187,-0.000758,39.166870,9.144703
5586,25,9,2024-10-07T00:00:00+00:00,1904.257446,0.027955,-0.000008,0.000005,0.129724,-0.001160,39.166870,9.144703
5587,25,9,2024-10-08T00:00:00+00:00,1904.257446,0.027955,0.000359,0.000006,0.126505,-0.001160,39.166870,9.144703
5588,25,9,2024-10-09T00:00:00+00:00,1904.257446,0.027955,0.000359,0.000006,0.137413,-0.001160,39.166870,9.144703

In [19]:
cells = [[df[(df['row'] == i) & (df['col'] == j)] for j in range(7, 10)] for i in range(21, 26)]
for row in cells:
    print(*[len(df) for df in row], sep='\t')

43	43	43
43	43	46
49	49	46
49	45	46
45	45	45

In [22]:
cells[0][0]

,row,col,entry_date,CH4,CO,HCHO,NO2,O3,SO2,lat,lon
867,21,7,2024-09-07 00:00:00+00:00,1926.995728,0.035737,1.960655e-04,0.000020,0.135583,0.000933,39.293112,9.017402
868,21,7,2024-09-08 00:00:00+00:00,1926.995728,0.030115,3.440966e-04,0.000033,0.130875,-0.000773,39.293112,9.017402
869,21,7,2024-09-09 00:00:00+00:00,1935.190796,0.030255,3.498628e-04,0.000046,0.127542,0.001538,39.293112,9.017402
870,21,7,2024-09-10 00:00:00+00:00,1902.401855,0.034752,-1.938203e-05,0.000023,0.139390,-0.000173,39.293112,9.017402
871,21,7,2024-09-11 00:00:00+00:00,1902.401855,0.036204,1.482278e-04,0.000008,0.141599,0.000210,39.293112,9.017402
872,21,7,2024-09-12 00:00:00+00:00,1902.401855,0.036358,1.533821e-05,0.000022,0.143222,0.000240,39.293112,9.017402
873,21,7,2024-09-13 00:00:00+00:00,1902.401855,0.036358,1.533821e-05,0.000022,0.142678,0.000240,39.293112,9.017402
874,21,7,2024-09-14 00:00:00+00:00,1902.401855,0.033130,2.567692e-05,0.000020,0.137111,-0.001274,39.293112,9.017402
875,21,7,2024-09-15 00:00:00+00:00,1902.401855,0.026904,-6.432101e-05,0.000022,0.145633,-0.000130,39.293112,9.017402
876,21,7,2024-09-16 00:00:00+00:00,1902.401855,0.026937,NaN,NaN,NaN,NaN,39.293112,9.017402
877,21,7,2024-09-17 00:00:00+00:00,1902.401855,0.026937,NaN,NaN,NaN,NaN,39.293112,9.017402
878,21,7,2024-09-18 00:00:00+00:00,1902.401855,0.026937,NaN,NaN,NaN,NaN,39.293112,9.017402
879,21,7,2024-09-19 00:00:00+00:00,1902.401855,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
880,21,7,2024-09-20 00:00:00+00:00,1902.401855,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
881,21,7,2024-09-21 00:00:00+00:00,1902.401855,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
882,21,7,2024-09-22 00:00:00+00:00,1902.401855,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
3373,21,7,2024-09-16 00:00:00+00:00,NaN,NaN,1.953942e-04,0.000026,0.150075,0.000353,39.293112,9.017402
3374,21,7,2024-09-17 00:00:00+00:00,NaN,NaN,1.953942e-04,0.000026,0.144288,0.000353,39.293112,9.017402
3375,21,7,2024-09-18 00:00:00+00:00,NaN,NaN,1.180475e-04,0.000026,0.146809,0.000301,39.293112,9.017402
3376,21,7,2024-09-19 00:00:00+00:00,NaN,0.035901,7.442189e-05,0.000049,0.149721,0.000322,39.293112,9.017402
3377,21,7,2024-09-20 00:00:00+00:00,NaN,0.033852,5.178619e-05,0.000049,0.142093,0.000014,39.293112,9.017402
3378,21,7,2024-09-21 00:00:00+00:00,NaN,0.033852,5.178619e-05,0.000049,0.140668,0.000014,39.293112,9.017402
3379,21,7,2024-09-22 00:00:00+00:00,NaN,0.033852,5.178619e-05,0.000049,0.140668,0.000014,39.293112,9.017402
3380,21,7,2024-09-23 00:00:00+00:00,NaN,0.029765,-5.293475e-07,0.000035,0.140884,0.000105,39.293112,9.017402
3381,21,7,2024-09-24 00:00:00+00:00,NaN,0.033689,-1.471496e-05,0.000015,0.140597,0.000057,39.293112,9.017402
3382,21,7,2024-09-25 00:00:00+00:00,NaN,0.033529,-1.179575e-05,0.000015,0.140597,0.000057,39.293112,9.017402
3383,21,7,2024-09-26 00:00:00+00:00,NaN,0.036907,9.194291e-05,0.000041,0.141882,-0.000219,39.293112,9.017402
3384,21,7,2024-09-27 00:00:00+00:00,NaN,0.034175,-1.931864e-04,0.000038,0.133326,-0.000940,39.293112,9.017402
3385,21,7,2024-09-28 00:00:00+00:00,NaN,0.028266,1.029627e-04,0.000029,0.130985,-0.001162,39.293112,9.017402
3386,21,7,2024-09-29 00:00:00+00:00,NaN,0.028266,-1.255463e-05,0.000022,0.136059,0.000412,39.293112,9.017402
3387,21,7,2024-09-30 00:00:00+00:00,NaN,0.034764,3.220933e-05,0.000015,0.134723,0.000728,39.293112,9.017402
3388,21,7,2024-10-01 00:00:00+00:00,NaN,0.034764,-7.115964e-05,0.000056,0.129461,-0.000162,39.293112,9.017402
3389,21,7,2024-10-03 00:00:00+00:00,1926.615112,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
3390,21,7,2024-10-04 00:00:00+00:00,1926.615112,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
3391,21,7,2024-10-05 00:00:00+00:00,1926.615112,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
3392,21,7,2024-10-06 00:00:00+00:00,1926.615112,NaN,NaN,NaN,NaN,NaN,39.293112,9.017402
5260,21,7,2024-10-03 00:00:00+00:00,NaN,0.030098,-9.022706e-05,0.000020,0.134585,0.000056,39.293112,9.017402
5261,21,7,2024-10-04 00:00:00+00:00,NaN,0.030098,-9.022706e-05,0.000020,0.133323,0.000056,39.293112,9.017402
5262,21,7,2024-10-05 00:00:00+00:00,NaN,0.030487,-4.221493e-05,0.000010,0.141508,-0.000009,39.293112,9.017402
5263,21,7,2024-10-06 00:00:00+00:00,NaN,0.030487,-4.221493e-05,0.000010,0.131494,-0.000009,39.293112,9.017402
5264,21,7,2024-10-07 00:00:00+00:00,1939.768188,0.030271,1.315622e-04,0.000033,0.128316,-0.000594,39.293112,9.017402
5265,21,7,2024-10-08 00:00:00+00:00,1939.768188,0.026767,-4.632413e-05,0.000037,0.126591,0.001185,39.293112,9.017402
5266,21,7,2024-10-09 00:00:00+00:00,1939.768188,0.026767,-4.632413e-05,0.000037,0.137429,0.001185,39.293112,9.017402

In [39]:
c = cells[1][0]
# c = c.groupby('entry_date')
# c.mean(numeric_only=True)
c = c.groupby('entry_date').mean()
c.fillna(c.mean(axis=1), inplace=True)
c

,row,col,CH4,CO,HCHO,NO2,O3,SO2,lat,lon
entry_date,,,,,,,,,,
2024-09-07T00:00:00+00:00,22.0,7.0,1926.995728,0.034785,-1.595348e-04,0.000018,0.136297,0.000906,39.261574,9.017394
2024-09-08T00:00:00+00:00,22.0,7.0,1926.995728,0.030115,-1.993955e-04,0.000034,0.132813,-0.000430,39.261574,9.017394
2024-09-09T00:00:00+00:00,22.0,7.0,1932.544312,0.030255,3.498628e-04,0.000046,0.127542,0.001538,39.261574,9.017394
2024-09-10T00:00:00+00:00,22.0,7.0,1902.401855,0.035160,1.554377e-04,0.000024,0.139840,0.000553,39.261574,9.017394
2024-09-11T00:00:00+00:00,22.0,7.0,1902.401855,0.036204,8.014104e-06,0.000015,0.140922,0.000626,39.261574,9.017394
2024-09-12T00:00:00+00:00,22.0,7.0,1902.401855,0.036358,1.858001e-04,0.000023,0.142749,0.000169,39.261574,9.017394
2024-09-13T00:00:00+00:00,22.0,7.0,1902.401855,0.036358,1.858001e-04,0.000023,0.143496,0.000169,39.261574,9.017394
2024-09-14T00:00:00+00:00,22.0,7.0,1902.401855,0.033937,-9.490487e-06,0.000016,0.138955,0.000448,39.261574,9.017394
2024-09-15T00:00:00+00:00,22.0,7.0,1902.401855,0.032710,2.171195e-04,0.000021,0.143807,-0.000013,39.261574,9.017394
2024-09-16T00:00:00+00:00,22.0,7.0,1902.401855,0.038521,8.460071e-05,0.000020,0.149842,0.000175,39.261574,9.017394
2024-09-17T00:00:00+00:00,22.0,7.0,1902.401855,0.038490,8.460071e-05,0.000020,0.143894,0.000175,39.261574,9.017394
2024-09-18T00:00:00+00:00,22.0,7.0,1902.401855,0.038490,5.088759e-05,0.000020,0.146681,0.000135,39.261574,9.017394
2024-09-19T00:00:00+00:00,22.0,7.0,1902.401855,0.038490,7.442189e-05,0.000049,0.149721,0.000322,39.261574,9.017394
2024-09-20T00:00:00+00:00,22.0,7.0,1902.401855,0.033852,5.178619e-05,0.000049,0.142093,0.000014,39.261574,9.017394
2024-09-21T00:00:00+00:00,22.0,7.0,1902.401855,0.036375,5.178619e-05,0.000049,0.140668,0.000014,39.261574,9.017394
2024-09-22T00:00:00+00:00,22.0,7.0,1902.401855,0.036375,5.178619e-05,0.000049,0.140668,0.000014,39.261574,9.017394
2024-09-23T00:00:00+00:00,22.0,7.0,NaN,0.029563,-5.293475e-07,0.000035,0.140884,0.000105,39.261574,9.017394
2024-09-24T00:00:00+00:00,22.0,7.0,NaN,0.033689,1.339391e-04,0.000024,0.140605,0.000157,39.261574,9.017394
2024-09-25T00:00:00+00:00,22.0,7.0,NaN,0.033529,1.400570e-04,0.000024,0.140605,0.000157,39.261574,9.017394
2024-09-26T00:00:00+00:00,22.0,7.0,NaN,0.036907,9.194291e-05,0.000041,0.141882,-0.000219,39.261574,9.017394
2024-09-27T00:00:00+00:00,22.0,7.0,NaN,0.035248,7.133716e-05,0.000035,0.131603,0.000642,39.261574,9.017394
2024-09-28T00:00:00+00:00,22.0,7.0,NaN,0.026888,-1.697628e-04,0.000035,0.131239,0.000331,39.261574,9.017394
2024-09-29T00:00:00+00:00,22.0,7.0,NaN,0.026888,2.939913e-05,0.000015,0.135396,-0.000604,39.261574,9.017394
2024-09-30T00:00:00+00:00,22.0,7.0,NaN,0.034764,1.797621e-04,0.000031,0.132795,-0.000030,39.261574,9.017394
2024-10-01T00:00:00+00:00,22.0,7.0,NaN,0.034764,7.005974e-05,0.000039,0.129794,0.000542,39.261574,9.017394
2024-10-03T00:00:00+00:00,22.0,7.0,1938.207642,0.030058,-5.527644e-06,0.000022,0.135241,-0.000502,39.261574,9.017394
2024-10-04T00:00:00+00:00,22.0,7.0,1938.207642,0.030058,-5.527644e-06,0.000022,0.134063,-0.000502,39.261574,9.017394
2024-10-05T00:00:00+00:00,22.0,7.0,1938.207642,0.030952,-4.221493e-05,0.000010,0.141508,-0.000009,39.261574,9.017394
2024-10-06T00:00:00+00:00,22.0,7.0,1938.207642,0.030952,-4.221493e-05,0.000010,0.133478,-0.000009,39.261574,9.017394
2024-10-07T00:00:00+00:00,22.0,7.0,1921.271362,0.029853,2.144832e-04,0.000024,0.128274,0.000460,39.261574,9.017394
2024-10-08T00:00:00+00:00,22.0,7.0,1921.271362,0.029853,1.116943e-04,0.000026,0.127530,0.001618,39.261574,9.017394
2024-10-09T00:00:00+00:00,22.0,7.0,1921.271362,0.029853,1.116943e-04,0.000026,0.136654,0.001618,39.261574,9.017394

In [21]:
# fill missing days
def fill_missing_days(df):
    df['entry_date'] = pd.to_datetime(df['entry_date'])
    df = df.set_index('entry_date')
    idx = pd.date_range(df.index.min(), df.index.max())
    df = df.reindex(idx)
    return df

/var/folders/sv/9dcz9m3116x4jvdkxys5yp5c0000gn/T/ipykernel_1615/1288765046.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['entry_date'] = pd.to_datetime(df['entry_date'])

ValueError: cannot reindex on an axis with duplicate labels

In [5]:
# Display initial info about NaN values
print("Initial NaN count per column:")
print(df.isnull().sum())

# Option 1: Remove rows with any NaN values
df_clean = df.dropna()

# Option 2: Fill NaN values with mean of the column
#df10_clean = df10.fillna(df10_clean.mean())

# Option 3: Fill NaN values with median of the column
# df_clean = df.fillna(df.median())

# Option 4: Fill NaN values with 0
df_clean = df.fillna(0)

print("\nShape before cleaning:", df.shape)
print("Shape after cleaning:", df_clean.shape)
dfw.describe()

Initial NaN count per column:
row              0
col              0
entry_date       0
geometry         0
centroid         0
CH4           2271
CO             567
HCHO           422
NO2            478
O3             345
SO2            479
dtype: int64

Shape before cleaning: (2681, 11)
Shape after cleaning: (2681, 11)

,row,col,CH4,CO,HCHO,NO2,O3,SO2
count,2681.000000,2681.000000,410.000000,2114.000000,2259.000000,2203.000000,2336.000000,2202.000000
mean,21.208877,8.800075,1921.633528,0.033051,0.000087,0.000019,0.139939,0.000090
std,3.811463,3.125416,29.800609,0.003706,0.000126,0.000011,0.006073,0.000689
min,15.000000,4.000000,1831.705811,0.017297,-0.000329,-0.000019,0.127651,-0.001486
25%,18.000000,6.000000,1917.730591,0.030282,0.000004,0.000012,0.134180,-0.000262
50%,21.000000,9.000000,1931.399048,0.032992,0.000082,0.000018,0.141225,0.000037
75%,24.000000,12.000000,1937.144531,0.036041,0.000162,0.000026,0.143775,0.000383
max,28.000000,14.000000,1967.712036,0.048617,0.000501,0.000066,0.152051,0.004524

In [9]:
df_clean.head

<bound method NDFrame.head of       row  col                 entry_date  \
0      15    5  2024-09-16T00:00:00+00:00
1      15    5  2024-09-17T00:00:00+00:00
2      15    5  2024-09-18T00:00:00+00:00
3      15    5  2024-09-19T00:00:00+00:00
4      15    5  2024-09-20T00:00:00+00:00
...   ...  ...                        ...
2676   28   14  2024-09-27T00:00:00+00:00
2677   28   14  2024-09-28T00:00:00+00:00
2678   28   14  2024-09-29T00:00:00+00:00
2679   28   14  2024-09-30T00:00:00+00:00
2680   28   14  2024-10-01T00:00:00+00:00

                                               geometry  \
0     {"type":"Polygon","coordinates":[[[8.857534478...
1     {"type":"Polygon","coordinates":[[[8.857534478...
2     {"type":"Polygon","coordinates":[[[8.857534478...
3     {"type":"Polygon","coordinates":[[[8.857534478...
4     {"type":"Polygon","coordinates":[[[8.857534478...
...                                                 ...
2676  {"type":"Polygon","coordinates":[[[9.430715591...
2677  {"type":"Polygon","coordinates":[[[9.430715591...
2678  {"type":"Polygon","coordinates":[[[9.430715591...
2679  {"type":"Polygon","coordinates":[[[9.430715591...
2680  {"type":"Polygon","coordinates":[[[9.430715591...

                                               centroid  CH4        CO  \
0     {"type":"Point","coordinates":[8.889543024,39....  0.0  0.000000
1     {"type":"Point","coordinates":[8.889543024,39....  0.0  0.000000
2     {"type":"Point","coordinates":[8.889543024,39....  0.0  0.032771
3     {"type":"Point","coordinates":[8.889543024,39....  0.0  0.035907
4     {"type":"Point","coordinates":[8.889543024,39....  0.0  0.032915
...                                                 ...  ...       ...
2676  {"type":"Point","coordinates":[9.46240891,39.0...  0.0  0.000000
2677  {"type":"Point","coordinates":[9.46240891,39.0...  0.0  0.000000
2678  {"type":"Point","coordinates":[9.46240891,39.0...  0.0  0.000000
2679  {"type":"Point","coordinates":[9.46240891,39.0...  0.0  0.000000
2680  {"type":"Point","coordinates":[9.46240891,39.0...  0.0  0.000000

          HCHO       NO2        O3       SO2
0     0.000152  0.000022  0.152051  0.000515
1     0.000225  0.000022  0.145941  0.000561
2     0.000205  0.000015  0.146785 -0.000569
3     0.000197  0.000015  0.146216 -0.000569
4     0.000027  0.000015  0.143961 -0.000003
...        ...       ...       ...       ...
2676  0.000019  0.000019  0.130171  0.001030
2677  0.000035  0.000004  0.131645 -0.000314
2678  0.000255  0.000015  0.134342  0.000904
2679  0.000004  0.000005  0.132796  0.000806
2680  0.000190  0.000033  0.129166  0.000565

[2681 rows x 11 columns]>

In [10]:
df_clean['row']

0       15
1       15
2       15
3       15
4       15
        ..
2676    28
2677    28
2678    28
2679    28
2680    28
Name: row, Length: 2681, dtype: int64

In [12]:
df_clean['col']

0        5
1        5
2        5
3        5
4        5
        ..
2676    14
2677    14
2678    14
2679    14
2680    14
Name: col, Length: 2681, dtype: int64

In [23]:
df_clean.centroid.unique()

array(['{"type":"Point","coordinates":[8.889543024,39.48228712]}',
       '{"type":"Point","coordinates":[8.953495844,39.482330282]}',
       '{"type":"Point","coordinates":[9.017448745,39.482338272]}',
       '{"type":"Point","coordinates":[9.081401615,39.482311089]}',
       '{"type":"Point","coordinates":[9.145354343,39.482248735]}',
       '{"type":"Point","coordinates":[9.209306816,39.482151208]}',
       '{"type":"Point","coordinates":[9.273258923,39.48201851]}',
       '{"type":"Point","coordinates":[9.33721055,39.481850641]}',
       '{"type":"Point","coordinates":[9.401161587,39.481647602]}',
       '{"type":"Point","coordinates":[8.825669106,39.450671718]}',
       '{"type":"Point","coordinates":[8.889592871,39.450749965]}',
       '{"type":"Point","coordinates":[8.95351683,39.450793079]}',
       '{"type":"Point","coordinates":[9.01744087,39.45080106]}',
       '{"type":"Point","coordinates":[9.08136488,39.450773908]}',
       '{"type":"Point","coordinates":[9.145288747,39.450711623]}',
       '{"type":"Point","coordinates":[9.20921236,39.450614204]}',
       '{"type":"Point","coordinates":[9.273135607,39.450481654]}',
       '{"type":"Point","coordinates":[9.337058376,39.450313972]}',
       '{"type":"Point","coordinates":[9.400980555,39.450111159]}',
       '{"type":"Point","coordinates":[9.464902032,39.449873217]}',
       '{"type":"Point","coordinates":[8.82574769,39.419134479]}',
       '{"type":"Point","coordinates":[8.88964264,39.419212639]}',
       '{"type":"Point","coordinates":[8.953537784,39.419255705]}',
       '{"type":"Point","coordinates":[9.017433008,39.419263677]}',
       '{"type":"Point","coordinates":[9.081328203,39.419236555]}',
       '{"type":"Point","coordinates":[9.145223255,39.419174339]}',
       '{"type":"Point","coordinates":[9.209118053,39.419077029]}',
       '{"type":"Point","coordinates":[9.273012485,39.418944627]}',
       '{"type":"Point","coordinates":[9.336906441,39.418777131]}',
       '{"type":"Point","coordinates":[9.400799807,39.418574545]}',
       '{"type":"Point","coordinates":[9.464692473,39.418336867]}',
       '{"type":"Point","coordinates":[8.825826151,39.387597068]}',
       '{"type":"Point","coordinates":[8.889692331,39.387675141]}',
       '{"type":"Point","coordinates":[8.953558705,39.387718159]}',
       '{"type":"Point","coordinates":[9.017425159,39.387726122]}',
       '{"type":"Point","coordinates":[9.081291583,39.38769903]}',
       '{"type":"Point","coordinates":[9.145157865,39.387636884]}',
       '{"type":"Point","coordinates":[9.209023893,39.387539683]}',
       '{"type":"Point","coordinates":[9.272889557,39.387407427]}',
       '{"type":"Point","coordinates":[9.336754744,39.387240119]}',
       '{"type":"Point","coordinates":[9.400619343,39.387037758]}',
       '{"type":"Point","coordinates":[9.464483243,39.386800345]}',
       '{"type":"Point","coordinates":[8.825904488,39.356059486]}',
       '{"type":"Point","coordinates":[8.889741944,39.356137472]}',
       '{"type":"Point","coordinates":[8.953579592,39.356180442]}',
       '{"type":"Point","coordinates":[9.017417321,39.356188396]}',
       '{"type":"Point","coordinates":[9.08125502,39.356161335]}',
       '{"type":"Point","coordinates":[9.145092577,39.356099257]}',
       '{"type":"Point","coordinates":[9.208929881,39.356002164]}',
       '{"type":"Point","coordinates":[9.272766821,39.355870056]}',
       '{"type":"Point","coordinates":[9.336603285,39.355702934]}',
       '{"type":"Point","coordinates":[9.400439162,39.355500799]}',
       '{"type":"Point","coordinates":[9.464274341,39.355263651]}',
       '{"type":"Point","coordinates":[8.825982703,39.324521732]}',
       '{"type":"Point","coordinates":[8.889791479,39.324599631]}',
       '{"type":"Point","coordinates":[8.953600448,39.324642553]}',
       '{"type":"Point","coordinates":[9.017409496,39.324650499]}',
       '{"type":"Point","coordinates":[9.081218515,39.324623467]}',
       '{"type":"Point","coordinates":[9.145027392,39.324561459]}',
       '{"type":"Point","coordinates":[9.208836017,39.324464474]}',
       '{"type":"Point","coordinates":[9.272644278,39.324332514]}',
       '{"type":"Point","coordinates":[9.336452064,39.324165578]}',
       '{"type":"Point","coordinates":[9.400259264,39.323963668]}',
       '{"type":"Point","coordinates":[9.464065768,39.323726785]}',
       '{"type":"Point","coordinates":[8.826060795,39.292983807]}',
       '{"type":"Point","coordinates":[8.889840937,39.293061619]}',
       '{"type":"Point","coordinates":[8.95362127,39.293104493]}',
       '{"type":"Point","coordinates":[9.017401684,39.29311243]}',
       '{"type":"Point","coordinates":[9.081182067,39.293085428]}',
       '{"type":"Point","coordinates":[9.144962309,39.293023489]}',
       '{"type":"Point","coordinates":[9.2087423,39.292926613]}',
       '{"type":"Point","coordinates":[9.272521927,39.292794799]}',
       '{"type":"Point","coordinates":[9.33630108,39.29262805]}',
       '{"type":"Point","coordinates":[9.400079648,39.292426365]}',
       '{"type":"Point","coordinates":[9.463857521,39.292189746]}',
       '{"type":"Point","coordinates":[8.826138765,39.26144571]}',
       '{"type":"Point","coordinates":[8.889890317,39.261523435]}',
       '{"type":"Point","coordinates":[8.95364206,39.261566262]}',
       '{"type":"Point","coordinates":[9.017393883,39.261574189]}',
       '{"type":"Point","coordinates":[9.081145677,39.261547218]}',
       '{"type":"Point","coordinates":[9.144897329,39.261485348]}',
       '{"type":"Point","coordinates":[9.20864873,39.26138858]}',
       '{"type":"Point","coordinates":[9.272399768,39.261256913]}',
       '{"type":"Point","coordinates":[9.336150333,39.26109035]}',
       '{"type":"Point","coordinates":[9.399900314,39.26088889]}',
       '{"type":"Point","coordinates":[9.463649601,39.260652534]}',
       '{"type":"Point","coordinates":[8.826216612,39.229907441]}',
       '{"type":"Point","coordinates":[8.889939619,39.22998508]}',
       '{"type":"Point","coordinates":[8.953662817,39.230027859]}',
       '{"type":"Point","coordinates":[9.017386095,39.230035778]}',
       '{"type":"Point","coordinates":[9.081109343,39.230008837]}',
       '{"type":"Point","coordinates":[9.14483245,39.229947036]}',
       '{"type":"Point","coordinates":[9.208555306,39.229850375]}',
       '{"type":"Point","coordinates":[9.272277801,39.229718856]}',
       '{"type":"Point","coordinates":[9.335999823,39.229552478]}',
       '{"type":"Point","coordinates":[9.399721262,39.229351243]}',
       '{"type":"Point","coordinates":[9.463442007,39.229115151]}',
       '{"type":"Point","coordinates":[8.826294337,39.198369002]}',
       '{"type":"Point","coordinates":[8.889988844,39.198446554]}',
       '{"type":"Point","coordinates":[8.953683541,39.198489285]}',
       '{"type":"Point","coordinates":[9.017378319,39.198497195]}',
       '{"type":"Point","coordinates":[9.081073066,39.198470284]}',
       '{"type":"Point","coordinates":[9.144767673,39.198408552]}',
       '{"type":"Point","coordinates":[9.208462029,39.198311999]}',
       '{"type":"Point","coordinates":[9.272156024,39.198180627]}',
       '{"type":"Point","coordinates":[9.335849548,39.198014434]}',
       '{"type":"Point","coordinates":[9.39954249,39.197813424]}',
       '{"type":"Point","coordinates":[9.463234739,39.197577595]}',
       '{"type":"Point","coordinates":[8.826371941,39.166830391]}',
       '{"type":"Point","coordinates":[8.890037992,39.166907856]}',
       '{"type":"Point","coordinates":[8.953704233,39.16695054]}',
       '{"type":"Point","coordinates":[9.017370555,39.166958441]}',
       '{"type":"Point","coordinates":[9.081036847,39.16693156]}',
       '{"type":"Point","coordinates":[9.144702998,39.166869897]}',
       '{"type":"Point","coordinates":[9.208368899,39.166773452]}',
       '{"type":"Point","coordinates":[9.272034439,39.166642226]}',
       '{"type":"Point","coordinates":[9.335699509,39.166476219]}',
       '{"type":"Point","coordinates":[9.399363998,39.166275433]}',
       '{"type":"Point","coordinates":[9.463027796,39.166039868]}',
       '{"type":"Point","coordinates":[8.826449422,39.135291609]}',
       '{"type":"Point","coordinates":[8.890087063,39.135368987]}',
       '{"type":"Point","coordinates":[8.953724893,39.135411623]}',
       '{"type":"Point","coordinates":[9.017362803,39.135419516]}',
       '{"type":"Point","coordinates":[9.081000684,39.135392665]}',
       '{"type":"Point","coordinates":[9.144638424,39.13533107]}',
       '{"type":"Point","coordinates":[9.208275914,39.135234733]}',
       '{"type":"Point","coordinates":[9.271913045,39.135103654]}',
       '{"type":"Point","coordinates":[9.335549705,39.134937832]}',
       '{"type":"Point","coordinates":[9.399185786,39.13473727]}',
       '{"type":"Point","coordinates":[9.462821177,39.134501968]}',
       '{"type":"Point","coordinates":[8.826526783,39.103752655]}',
       '{"type":"Point","coordinates":[8.890136057,39.103829947]}',
       '{"type":"Point","coordinates":[8.95374552,39.103872536]}',
       '{"type":"Point","coordinates":[9.017355064,39.103880419]}',
       '{"type":"Point","coordinates":[9.080964577,39.103853598]}',
       '{"type":"Point","coordinates":[9.335400136,39.103399274]}',
       '{"type":"Point","coordinates":[9.399007853,39.103198936]}',
       '{"type":"Point","coordinates":[9.462614882,39.102963896]}',
       '{"type":"Point","coordinates":[8.826604022,39.07221353]}',
       '{"type":"Point","coordinates":[8.890184974,39.072290736]}',
       '{"type":"Point","coordinates":[8.953766115,39.072333277]}',
       '{"type":"Point","coordinates":[9.017347336,39.072341152]}',
       '{"type":"Point","coordinates":[9.080928528,39.072314361]}',
       '{"type":"Point","coordinates":[9.335250802,39.071860544]}',
       '{"type":"Point","coordinates":[9.3988302,39.071660429]}',
       '{"type":"Point","coordinates":[9.46240891,39.071425652]}'],
      dtype=object)

In [18]:
dfrow = dfcol.loc[dfcol['row'] == 15]

In [20]:
dfrow.describe

<bound method NDFrame.head of Empty DataFrame
Columns: [row, col, entry_date, geometry, centroid, CH4, CO, HCHO, NO2, O3, SO2]
Index: []>

In [21]:
dfrow.head

<bound method NDFrame.head of Empty DataFrame
Columns: [row, col, entry_date, geometry, centroid, CH4, CO, HCHO, NO2, O3, SO2]
Index: []>

In [ ]:
fig = plt.figure(figsize=(20, 12))

# Define grid layout
gs = fig.add_gridspec(2, 2)

# 1. Line plots of all numeric columns
ax1 = fig.add_subplot(gs[0, :])  # Top row, full width


new_cols3m2=new_cols3[1:-1]
# Plot each numeric column
for column in new_cols3m2:
    # Normalize data to make trends comparable
    normalized_data = new_df001[column]
    ax1.plot(normalized_data.index, normalized_data, label=column, linewidth=2, alpha=0.7)

ax1.set_title('Normalized Data Trends Over Time P2.5', pad=20)
ax1.set_xlabel('Index')
ax1.set_ylabel('Normalized Values')
ax1.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
ax1.grid(True, linestyle='--', alpha=0.7)